### ISSUE TITLE
关于项目搭建

### ISSUE THREAD

**Issue by MadridSeven** [yilong0722/hdfs-web#1]
话说我在我电脑本地怎么搭建？

**Comment by longshilin** [comment]
关于项目的环境的搭建：
- [Hadoop集群环境搭建](http://blog.csdn.net/Coder__CS/article/category/7254744)
- eclipse开发平台的准备
- tomcat本地服务器

关于项目的具体实施，有如下几点说明：
项目的主体用 jsp+servlet，基于mvc模式搭建，其中文件的上传下载利用了apache common包，具体见code。
核心部分 利用HDFS API，详细见code。

你可以先把项目代码fork到你本地电脑，通过查看源代码，可以较清晰的了解项目。具体问题再issue~
