### ISSUE TITLE
关于项目维护

### ISSUE THREAD

**Issue by Big-Carson** [yilong0722/hdfs-web#2]
请问一下，项目还在维护不，我已经在本地搭建好了， 不错过貌似还有一些功能(比如注册，以及上传文件到hdfs中等）都没有实现。

**Comment by longshilin** [comment]
你好，很高兴能收到你的消息，首先感谢你对这个项目感兴趣~

关于是否再维护，我给出的答案的是：目前未维护 但是有打算未来会继续维护。因此如果你有好的idea或者demo可以一起分享交流，我秉着开源的精神来看待此项目~
另外你提到的几点功能，这里我说明下：
1. 没有实现复杂的注册功能，只有简单的表单校验
2. 项目目前的状态是可以支持文件的上传、下载、删除等操作的，可以详细查看源码了解

希望收到你的回复~谢谢

**Comment by Big-Carson** [comment]
你好，我对这个项目很有兴趣的，目前正在仔细阅读代码理解功能实现中，希望以后可以参与学习。谢谢~

**Comment by longshilin** [comment]
好的，听到你说对该项目很感兴趣，我非常高兴~  由于近期忙于自己的工作，所以会在未来的某个时间重构代码。
让我们一起来维护项目、互相学习~

**Comment by Big-Carson** [comment]
好的好的，谢谢~
