### ISSUE TITLE
代码重复问题

### ISSUE THREAD

**Issue by Big-Carson** [yilong0722/hdfs-web#4]
你好，请问一下，我发现有两个文件夹，都是相同的代码，然后我用的是src/main下面的(里面有resources)，另一个是src/com/elon33,以后你维护的话，代码更新在哪边呢？是否可以删掉src/com/elon33？

**Comment by longshilin** [comment]
@Big-Carson  嗯 这个应该是以前我用eclipse和idea都开发过，在不同平台之间导入项目时出现文件重复的问题，以后统一在main目录下面做开发~  另外我把src/com/elon33这个文件夹去除
